const blogs = [
    {
        id: '1',
        title: '[MEDIUM] The story of climate change and Covid-19 pandemic.',
        screens: 'https://cdn-images-1.medium.com/max/600/1*ezlv7DqjbhnO9FJuvdcdKg.png',
        description: 'Consectetur adipiscing elit. Purusout phasellus malesuada lectus.',
        author: 'Marilou Kelleher',
        authorTitle:'Sineor Consultant',
        create_at: '25 Dec, 2020',
        blogSingleImg:'images/blog-details/img-1.jpg', 
        comment:'35',
        blClass:'format-standard-image',
        link:'https://link.medium.com/iUojpkY748',
    },
    {
        id: '2',
        title: 'Updating...',
        screens: 'images/blog/img-2.jpg',
        description: 'Consectetur adipiscing elit. Purusout phasellus malesuada lectus.',
        author: 'Konal Biry',
        authorTitle:'Creative Director',
        create_at: '13 Dec,2022',
        blogSingleImg:'images/blog-details/img-2.jpg', 
        comment:'80',
        blClass:'format-standard-image',
    },
    {
        id: '3',
        title: 'Updating...',
        screens: 'images/blog/img-3.jpg',
        description: 'Consectetur adipiscing elit. Purusout phasellus malesuada lectus.',
        author: 'Aliza Anny',
        authorTitle:'Art Director',
        create_at: '22 Dec,2022',
        blogSingleImg:'images/blog-details/img-3.jpg',
        comment:'95',
        blClass:'format-video',
    },
    {
        id: '4',
        title: 'Updating...',
        screens: 'images/blog/img-2.jpg',
        description: 'Consectetur adipiscing elit. Purusout phasellus malesuada lectus.',
        author: 'Konal Biry',
        authorTitle:'Creative Director',
        create_at: '13 Dec,2022',
        blogSingleImg:'images/blog-details/img-2.jpg', 
        comment:'80',
        blClass:'format-standard-image',
    },
];
export default blogs;